### PR TITLE
Use self instead of SimpleMemoryBackend

### PR DESCRIPTION
**Pull request by and-semakin**
## What do these changes do?

Use `self` instead of direct links to `SimpleMemoryBackend` class. This PR doesn't affect any functionality but allows users of the library inherit `SimpleMemoryBackend` and change its behaviour. Otherwise, changing the behavior is really difficult to do.

## Are there changes in behavior for the user?

No.

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by Fogapod** [comment]
This is not a correct fix since you still use global cache and handlers. They are not set on init

**Comment by and-semakin** [comment]
@Fogapod exactly, I didn’t even try to fix the issue with global cache state. My only purpose here was just to make inheritance easier. It’s just one little step in the correct direction.

**Comment by Dreamsorcerer** [comment]
Looks good, sorry for the delay. Could you update with latest master and ensure the tests are all passing. Thanks.

**Comment by Dreamsorcerer** [comment]
I think this is solved now with #562. Please reopen if not.

**Pull request closed without merging**
